spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cine_db2?createDatabaseIfNotExist=true
    username: root
    password: hpto1capo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

jwt:
  secret: "tu_clave_secreta_muy_segura_minimo_32_caracteres_para_hs256"
  expiration: 86400000  # 24 horas en milisegundos

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    show-common-extensions: true
    show-extensions: true
  use-fqn: true

file:
  upload-dir: uploads
